[tool.poetry]
name = "plexure-api-search"
version = "2.0.0"
description = "Advanced API search with triple vector embeddings and contextual boosting"
authors = ["Plexure <dev@plexure.com>"]
readme = "README.md"
packages = [{ include = "plexure_api_search" }]

[tool.poetry.dependencies]
python = "^3.12"
pinecone-client = "^3.0.0"
sentence-transformers = "^2.2.2"
numpy = "^1.24.3"
spacy = "^3.6.1"
networkx = "^3.1"
fastapi = "^0.100.0"
uvicorn = "^0.23.1"
python-dotenv = "^1.0.0"
pydantic = "^2.0.3"
openapi-spec-validator = "^0.6.0"
requests = "^2.31.0"
tqdm = "^4.65.0"
scikit-learn = "^1.3.0"
rich = "^13.0.0"
click = "^8.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.1.0"
isort = "^5.12.0"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
plexure-api-search = "plexure_api_search.cli:cli"
