[tool.poetry]
name = "plexure-api-search"
version = "2.0.0"
description = "Advanced API search with triple vector embeddings and contextual boosting"
authors = ["Plexure <dev@plexure.com>"]
readme = "README.md"
packages = [{ include = "plexure_api_search" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
numpy = ">=2.0.0,<2.1.0"
spacy = ">=3.8.0,<3.8.3"
pinecone-client = "^5.0.1"
sentence-transformers = "^3.3.1"
networkx = "^3.1"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
python-dotenv = "^1.0.0"
pydantic = "^2.0.3"
openapi-spec-validator = "^0.7.1"
requests = "^2.31.0"
tqdm = "^4.65.0"
scikit-learn = "^1.3.0"
rich = "^13.0.0"
click = "^8.0.0"
diskcache = "^5.6.3"
faiss-cpu = "^1.9.0.post1"
httpx = "^0.28.1"

[tool.poetry.group.dev.dependencies]
black = "^24.1.0"
isort = "^5.12.0"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
plexure-api-search = "plexure_api_search.cli:cli"
