openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: Example API for testing

paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticate user and return access token
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /auth/register:
    post:
      summary: User registration
      description: Register a new user
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '409':
          description: Username already exists

  /auth/logout:
    post:
      summary: User logout
      description: Invalidate current user session
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
        '401':
          description: Unauthorized

  /auth/refresh:
    post:
      summary: Refresh token
      description: Get new access token using refresh token
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid refresh token

  /users/me:
    get:
      summary: Get current user
      description: Get details of the currently authenticated user
      tags:
        - users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User details retrieved successfully
        '401':
          description: Unauthorized
        '404':
          description: User not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 